<?php
/*
 * Copyright © 2025 rainier39 <rainier39@proton.me>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// default_config.php
// Stores the default configuration for the software.

// Only load the page if it's being requested via the index file.
if (!defined('INDEX')) exit;

// DO NOT EDIT THIS FILE. All configuration should be done in config.php.
$default_config = array(
    "version" => "v2.5.0-alpha",
    "installed" => false,
    "dir" => "",
    "SQLServer" => "",
    "SQLDatabase" => "",
    "SQLUsername" => "",
    "SQLPassword" => "",
    "title" => "AtomicBlog",
    "description" => "A lightweight, easy to use, and easy to administrate blogging software.",
    "footer" => "Powered by [AtomicBlog](https://github.com/rainier39/AtomicBlog)",
    "theme" => "Light",
    "language" => "english",
    // Whether to redirect all HTTP requests to HTTPS.
    "https" => false,
    "prettyURLs" => false,
    // Whether to allow people to create accounts.
    "allowRegistration" => true,
    "loginsPerHour" => 5,
    "accountsPerIP" => 3,
    // How long a user must wait (in seconds) between creating accounts. 600 seconds = 10 minutes.
    "accountCooldown" => 600,
    // How long a user must wait (in seconds) between making blog posts. 300 seconds = 5 minutes.
    "postDelay" => 300,
    // How long a user must wait (in seconds) between editing blog posts.
    "editDelay" => 5
);

?>

