<?php
// config.php
// Stores the configuration for the software.

// Only load the page if it's being requested via the index file.
if (!defined('INDEX')) exit;

// DO NOT EDIT THIS FILE. All configuration should be done in config.php.
$default_config = array(
    "version" => "v2.0.0-alpha",
    "installed" => false,
    "dir" => "",
    "SQLServer" => "",
    "SQLDatabase" => "",
    "SQLUsername" => "",
    "SQLPassword" => "",
    "title" => "AtomicBlog",
    "description" => "A lightweight, easy to use, and easy to administrate blogging software.",
    "footer" => "Powered by [AtomicBlog](https://github.com/rainier39/AtomicBlog)",
    "theme" => "Light",
    "language" => "english",
    // Whether to redirect all HTTP requests to HTTPS.
    "https" => false,
    "prettyURLs" => false,
    // Whether to allow people to create accounts.
    "allowRegistration" => true,
    "loginsPerHour" => 5,
    "accountsPerIP" => 3,
    // How long a user must wait (in seconds) before creating another account. 600 seconds = 10 minutes.
    "accountCooldown" => 600,
    // How long a user must wait (in seconds) before creating another blog post. 300 seconds = 5 minutes.
    "postDelay" => 300
);

?>

